name: automerge
on:
  pull_request_review:
    types: [submitted]
jobs:
  pr-automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.2.2
      env:
        GITHUB_TOKEN: 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
      with:
        merge-method: 'merge' 
        min-approvals: 1
        base-ref: 'main'
