name: automerge
on:
  pull_request_review:
    types: [submitted]
jobs:
  pr-automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_METHOD: 'merge'
        MERGE_REQUIRED_APPROVALS: 1
