# name: Merge PR
# on:
#   workflow_run:
#     workflows: ["automerge"]
#     types:
#       - completed
# jobs:
#   pr-automerge:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: davideviolante/pr-automerge-action@v1.2.2
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         merge-method: 'merge' 
#         min-approvals: 1
#         base-ref: 'main'
