name: Merge PR
on:
  workflow_run:
    workflows: ["automerge"]
    types:
      - completed
jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "https://github.com/6233/jhleeO/pull/61"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
